apiVersion: v1
kind: Service
metadata:
  name: edgex-NODENAME
spec:
  ports:
  - name: consul
    port: 8500
    targetPort: 8500
    protocol: TCP
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  - name: ui
    port: 4000
    targetPort: 4000
    protocol: TCP
  - name: kuiper
    port: 59720
    targetPort: 59720
    protocol: TCP
  - name: app-mqtt-export
    port: 59703
    targetPort: 59703
    protocol: TCP
  - name: sys-mgmt-agent
    port: 58890
    targetPort: 58890
    protocol: TCP
  - name: app-rules-engine
    port: 59701
    targetPort: 59701
    protocol: TCP
  - name: core-command
    port: 59882
    targetPort: 59882
    protocol: TCP
  - name: core-data-59880
    port: 59880
    targetPort: 59880
    protocol: TCP
  - name: core-data-5563
    port: 5563
    targetPort: 5563
    protocol: TCP
  - name: device-virtual
    port: 59900
    targetPort: 59900
    protocol: TCP
  - name: core-metadata
    port: 59881
    targetPort: 59881
    protocol: TCP
  - name: support-notifications
    port: 59860
    targetPort: 59860
    protocol: TCP
  - name: support-scheduler
    port: 59861
    targetPort: 59861
    protocol: TCP
  - name: sync-app
    port: 59740
    targetPort: 59740
    protocol: TCP
  - name: device-rest
    port: 59986
    targetPort: 59986
    protocol: TCP      
  - name: device-lora
    port: 59999
    targetPort: 59999
    protocol: TCP
  - name: kong-db
    port: 5432
    targetPort: 5432
    protocol: TCP  
  - name: kong-8000
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: kong-8100
    port: 8100
    targetPort: 8100
    protocol: TCP
  - name: kong-8443
    port: 8443
    targetPort: 8443
    protocol: TCP
  - name: vault
    port: 8200
    targetPort: 8200
    protocol: TCP     
  selector:
    name: edgex-NODENAME
