---
- hosts: master
  connection: local
  tasks: 
    - name: Get join command data
      command:
        cmd: "kubeadm token create --print-join-command"
      register: kubeadm_join_cmd
    - name: Construct join command
      set_fact:
        join_cmd: "{{ kubeadm_join_cmd.stdout_lines[0] }}"

- hosts: edge_nodes
  tasks:
    - name: Join cluster
      become: true
      # NOTE: This relies on the master being the "localhost" node above.
      # FIXME: Output the result to a file to avoid joining when already joined?
      command:
        cmd: "{{ hostvars['localhost'].join_cmd }}"
        # chdir: $HOME
        # creates: node_join.txt
