---
- hosts: master
  tasks: 
    - name: Get join command data
      command:
        cmd: "kubeadm token create --print-join-command"
      register: kubeadm_join_cmd
    - name: Construct join command
      set_fact:
        join_cmd: "{{ kubeadm_join_cmd.stdout_lines[0] }}"

- hosts: edge_nodes
  tasks:
    - name: Join cluster
      become: true
      # NOTE: This relies on there being only one master node.
      # FIXME: Check if the node is already in the cluster and skip?
      command:
        cmd: "{{ hostvars[groups['master'][0]].join_cmd }}"
