---
- hosts: localhost
  connection: local
  vars:
    master_name: "{{ query('inventory_hostnames', 'master') }}"
    build_name: "{{ query('inventory_hostnames', 'build') }}"
    cicd_name: "{{ query('inventory_hostnames', 'cicd') }}"
  tasks: 
    - name: Install Basic Build Tools
      become: true
      apt:
        pkg:
          - make
          - build-essential
          - python3-pip
          - software-properties-common

    - name: Add Ansible repository
      # Required to get the latest version of Ansible
      # Ubuntu 20.04's default 2.9.6 does not play well with kubernetes.core
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:ansible/ansible
        state: present
    - name: Install Ansible
      become: true
      ansible.builtin.apt:
        pkg:
          - ansible
        state: latest

    - name: Test if community.docker is installed
      stat:
        path: ~/.ansible/collections/ansible_collections/community/docker/MANIFEST.json
      register: docker_collection
    - name: Install the community.docker collection
      command:
        cmd: ansible-galaxy collection install community.docker
      when: not docker_collection.stat.exists

    - name: Test if kubernetes.core is installed
      stat:
        path: ~/.ansible/collections/ansible_collections/kubernetes/core/MANIFEST.json
      register: kube_collection
    - name: Install the kubernetes.core collection
      # See http://blog.networktocode.com/post/kubernetes-collection-ansible/
      command:
        cmd: ansible-galaxy collection install kubernetes.core
      when: not kube_collection.stat.exists

    - name: Test if community.crypto is installed
      stat:
        path: ~/.ansible/collections/ansible_collections/community/crypto/MANIFEST.json
      register: crypto_collection
    - name: Install the community.crypto collection
      command:
        cmd: ansible-galaxy collection install community.crypto
      when: not crypto_collection.stat.exists

    # This is mainly used by robot framework scripts in cicd/tests/ directory
    - name: Add master name to /etc/hosts (if master name is not hostname)
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        state: present
        create: yes
        backup: yes
        regexp: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\\s+master"
        line: "{{ master_ip }} master"
        insertbefore: BOF
      when: (ansible_facts['nodename'] != 'master')
    # This is mainly used by ansible playbook scripts
    - name: Add master node to /etc/hosts (if master is not hostname)
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        state: present
        create: yes
        backup: yes
        regexp: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\\s+{{ master_name[0] }}"
        line: "{{ master_ip }} {{ master_name[0] }}"
        insertbefore: BOF
      when: (ansible_facts['nodename'] != master_name[0])
    # This is mainly used by ansible playbook script to install edge node from deploy node
    - name: Add edge nodes to /etc/hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        state: present
        create: yes
        backup: yes
        regexp: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\\s+{{ item }}"
        line: "{{ hostvars[item]['ip'] }} {{ item }}"
        insertbefore: BOF
      loop: "{{ query('inventory_hostnames', 'edge_nodes') }}"
    # This is mainly used by ansible playbook script to install build node from deploy node
    - name: Add build node to /etc/hosts (if build is not hostname)
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        state: present
        create: yes
        backup: yes
        regexp: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\\s+{{ build_name[0] }}"
        line: "{{ hostvars[build_name[0]]['ip'] }} {{ build_name[0] }}"
        insertbefore: BOF
      when: (ansible_facts['nodename'] != build_name[0])
    # This is mainly used by ansible playbook script to install cicd node from deploy node
    - name: Add cicd node to /etc/hosts (if cicd is not hostname)
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        state: present
        create: yes
        backup: yes
        regexp: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\\s+{{ cicd_name[0] }}"
        line: "{{ hostvars[cicd_name[0]]['ip'] }} {{ cicd_name[0] }}"
        insertbefore: BOF
      when: (ansible_facts['nodename'] != cicd_name[0])


