apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-service-mqtt-export-secrets-NODENAME
  labels:
    type: local
    app: app-service-mqtt-export-secrets
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/lfedge/volumes/edgex/secrets/app-mqtt-export
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NODENAME

