apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-config-NODENAME
  labels:
    type: local
    app: consul-config
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/lfedge/volumes/consul-config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NODENAME

