apiVersion: v1
kind: PersistentVolume
metadata:
  name: device-lora-secrets-NODENAME
  labels:
    type: local
    app: device-lora-secrets
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/lfedge/volumes/edgex/secrets/device-lora
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NODENAME
