apiVersion: v1
kind: PersistentVolume
metadata:
  name: device-camera-devices-NODENAME
  labels:
    type: local
    app: device-camera-devices
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/lfedge/volumes/edgex/devices/device-camera
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NODENAME