apiVersion: v1
kind: PersistentVolume
metadata:
  name: sync-app-secrets-NODENAME
  labels:
    type: local
    app: sync-app-secrets
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/lfedge/volumes/edgex/secrets/sync-app
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NODENAME

