---
- hosts: cicd
  vars:
    build_name: "{{ query('inventory_hostnames', 'build') }}"
  tasks: 
    - name: Add build node to file /etc/hosts 
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        state: present
        create: yes
        backup: yes
        regexp: "^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\\s+{{ build_name[0] }}"
        line: "{{ hostvars[build_name[0]]['ip'] }} {{ build_name[0] }}"
        insertbefore: BOF
      when: (ansible_facts['nodename'] != build_name[0])
    - name: Install Basic Build Tools
      become: true
      apt:
        pkg:
          - make
          - build-essential
          - python3-pip

    - name: Install JRE
      # JRE is a prerequisite for Jenkins
      become: true
      apt:
        pkg:
          - default-jre
    - name: Setup Jenkins key
      become: true
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
    - name: Setup Jenkins apt source
      become: true
      ansible.builtin.lineinfile:
        line: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        path: /etc/apt/sources.list.d/jenkins.list
        create: yes
    - name: Install Jenkins
      become: true
      apt:
        update_cache: yes
        pkg:
          - jenkins
