apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app-service-mqtt-export-claim1
  name: app-service-mqtt-export-secrets-NODENAME
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: app-service-mqtt-export-secrets
status: {}
