apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: consul-claim4
  name: consul-secrets-NODENAME
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: consul-secrets
status: {}
