apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: device-lora-secrets-NODENAME
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: device-lora-secrets
status: {}
