apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: device-rest-secrets-NODENAME
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: device-rest-secrets
status: {}
