apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: image-app-secrets-NODENAME
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: image-app-secrets
status: {}
