apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: sync-app-secrets-NODENAME
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: sync-app-secrets
status: {}
