#
# Copyright (c) 2020 Intel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG BASE=golang:1.16-alpine3.14
FROM --platform=linux/arm64 ${BASE} AS builder

ARG MAKE=make build

WORKDIR /device-lora

RUN sed -e 's/dl-cdn[.]alpinelinux.org/nl.alpinelinux.org/g' -i~ /etc/apk/repositories

RUN apk add --update --no-cache make git gcc libc-dev zeromq-dev libsodium-dev

COPY go.mod .
RUN go mod download all
COPY . .

RUN make cmd/device-lora

# Next image - Copy built Go binary into new workspace
FROM --platform=linux/arm64 alpine:3.14
LABEL license='SPDX-License-Identifier: Apache-2.0' \
  copyright='Copyright (c) 2022: Fujitsu Limited'

RUN sed -e 's/dl-cdn[.]alpinelinux.org/nl.alpinelinux.org/g' -i~ /etc/apk/repositories

RUN apk add --update --no-cache zeromq dumb-init

WORKDIR /
COPY --from=builder /device-lora/cmd/ /

EXPOSE 59999

ENTRYPOINT ["/device-lora"]
CMD ["-cp=consul.http://localhost:8500", "--registry", "--confdir=/res"]
