---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
clusterName: lfedge
imageRepository: master:5000
controlPlaneEndpoint: master_ip
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
apiServer:
  extraArgs:
    enable-admission-plugins: PodSecurityPolicy
kubernetesVersion: v1.22.9
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
nodeRegistration:
  name: master
  kubeletExtraArgs:
    node-ip: master_ip
